services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: prlab2_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: liviuiordan03
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: prlab2_db
      DB_USER: postgres
      DB_PASSWORD: liviuiordan03
    ports:
      - "5000:5000"
    volumes:
      - .:/app

volumes:
  data:
