services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: prlab2_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: liviuiordan03
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:
